apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: hoshinova
    namespace: media
spec:
    interval: 15m
    chart:
        spec:
            chart: app-template
            version: 14.2.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: hoshinova
    values:
        image:
        repository: alpine
        tag: latest
        command: ["/bin/sh", "-c", "sleep 3600"]  # Keeps the container running
        service:
        main:
            enabled: false  # Disable the main service
            port: 9104
            targetPort: 1104
            type: ClusterIP
        livenessProbe: {}  # Disable liveness probe
        readinessProbe: {}  # Disable readiness probe