apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - media
  - tautulli/ks.yaml
  - proxy-homeassistant/ks.yaml
  - ghostfolio/ks.yaml
  - actualserver/ks.yaml
  - actual-http-api/ks.yaml
  - cloudflareddns/ks.yaml
  - upsnap/ks.yaml
  - tailscale/ks.yaml
  - mariadb/ks.yaml
  - proxy-ha-code/ks.yaml
  - proxy-pihole/ks.yaml
  - proxy-router/ks.yaml
  - proxy-truenas/ks.yaml
  - mealie/ks.yaml
  - minio/ks.yaml
  - muse/ks.yaml
