apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: radarr
    namespace: media
spec:
    interval: 15m
    chart:
        spec:
            chart: radarr
            version: 22.2.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: radarr
    values:
        credentials:
            minio:
                accessKey: ${MINIO_ACCESSKEY}
                bucket: ${MINIO_BUCKET}
                encrKey: ${MINIO_ENCRKEY}
                secretKey: ${MINIO_SECRETKEY}
                type: s3
                url: ${MINIO_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: radarr.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
        persistence:
            config:
                volsync:
                    - credentials: minio
                      type: restic
                      name: config
                      dest:
                        enabled: true
                      src:
                        enabled: false
            media:
                enabled: true
                existingClaim: media-nfs-pvc
                mountPath: "/media"