apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ark-survival-ascended
  namespace: ark-survival-ascended
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 18.14.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: ark-survival-ascended
  values:
    image:
      repository: mschnitzer/asa-linux-server
      tag: 1.5.1
      pullPolicy: IfNotPresent
    workload:
      main:
        type: StatefulSet
        podSpec:
          containers:
            main:
              command:
                - /usr/bin/start_server
              env:
                ENABLE_DEBUG: "0"
                ASA_START_PARAMS: >-
                  TheIsland_WP?listen?Port=7777?RCONEnabled=True?RCONPort=27020?ServerAdminPassword=${ARK_ADMIN_PASSWORD}
                  -WinLiveMaxPlayers=10
                  -clusterid=default
                  -ClusterDirOverride="/home/gameserver/cluster-shared"
              lifecycle:
                preStop:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - "asa-ctrl rcon --exec 'saveworld'"
              probes:
                startup:
                  enabled: true
                  custom:
                    spec:
                      exec:
                        command:
                          - /bin/sh
                          - -c
                          - "asa-ctrl rcon --exec 'listplayers'"
                      initialDelaySeconds: 60
                      periodSeconds: 30
                      failureThreshold: 20
                readiness:
                  enabled: true
                  custom:
                    spec:
                      exec:
                        command:
                          - /bin/sh
                          - -c
                          - "asa-ctrl rcon --exec 'listplayers'"
                      periodSeconds: 30
                      failureThreshold: 3
                liveness:
                  enabled: true
                  custom:
                    spec:
                      exec:
                        command:
                          - /bin/sh
                          - -c
                          - "asa-ctrl rcon --exec 'listplayers'"
                      initialDelaySeconds: 300
                      periodSeconds: 60
                      failureThreshold: 5

    service:
      main:
        type: LoadBalancer
        ports:
          main:
            enabled: true
            port: 7777
            protocol: udp
            targetPort: 7777
          rcon:
            enabled: true
            port: 27020
            protocol: tcp
            targetPort: 27020
    persistence:
      steam:
        enabled: true
        mountPath: /home/gameserver/Steam
        size: 20Gi
      steamcmd:
        enabled: true
        mountPath: /home/gameserver/steamcmd
        size: 5Gi
      server-files:
        enabled: true
        mountPath: /home/gameserver/server-files
        size: 100Gi
      cluster-shared:
        enabled: true
        mountPath: /home/gameserver/cluster-shared
        size: 20Gi
    securityContext:
      container:
        runAsNonRoot: true
        runAsUser: 25000
        runAsGroup: 25000
      pod:
        fsGroup: 25000
    resources:
        requests:
            cpu: 10m
            memory: 2Gi
        limits:
            cpu: 4
            memory: 24Gi
    addons:
        codeserver:
            enabled: true
            ingress:
                enabled: true
                hosts:
                  - host: ark-codeserver.${DOMAIN_0}