apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:p3H5N5SeWnf1zp3AnCJrMsasnAwbAa5iBFe+nVgiwtwA/q2XcT06bfMh4tRcjvT0BcNPcqc3ZB3lTMiyy+6/celjlITSpFwbTwrSNwRPYs8ThxKvC4KBfbHfs1arUin7tcEZV9X5u9toBohsdXkLPsL+SYSqHUx3mCHaLxM2Qomxo9DDj7l75M2ZrDml0inoQWKnlAyqaZ2IJHDm7GAoMA7G/Re2BrOEQ4vCrw4rilg4ijxZnvNAHEzrMclcYNB+5enMEMcj8v340QWJvNWMs++u2a6wxFN96Y1saQiSjkmYp9Wj9Yk7cWPX4P8+OuCU0nBUAmaz0cibE6OaAJ0hOPUdhFgqHgnfWxpQEJxC4S90tA2OhaHxMM9+vB0rzRCc,iv:F0kqMMmdL+9wArfpJom1+9yAZwIcxCyVTxMpk8t4OPI=,tag:trKrBsTdhpo6EC1bYK6JuA==,type:str]
    identity.pub: ENC[AES256_GCM,data:7t8n4Ia6MOEZ0tm7Was9p2zgPWFa6yLvGb0jS4ZnCeSn7IgeF6ApjBxWfG65HN0CKJ5LleHefk8nylt5QyCYTvfX9FOfmMxYMVDP6IgwnVIl3UmYMRXhwK9ql5I5T9IeFXmL1LkYk1QLh3rpE2bXvpM6j7aRNdmSM72XGNLZSHjFDH0rKpTRuOOHDVqDfVgAPckCOUkHnTtsJOjWCXaBHs4EcSrG0+cdgM+u0DfKIIO5iqVyolWa+GfmLu5WyIveYXhSF0uzI9KmBwLFEw==,iv:sFGdD98NOc6UoCit560cs3IPpo7euGWkuTHLR6qVqaA=,tag:dVOuodKGlnxRmhjR2BHHHg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Qj+1ZD/l4eBQ/htyZiuQVQRTLgNVCtP9VnBEAm8/CnBanRM5aAGhk9coC0y5yFhCemC/cMV4YYiOHlN5stBqYGvMtl4Igzenda3WEC48CdRY5lwnH/xWYHpAfPMaPorvvZUkosSksiN+BwTLA1IplJmvhG9xLdsuCR9DtNjfKexb+fx1GDSH1p5XCfcKkjLKzwvSfnVDA1G7b/jwnGOXWejzLh2HzpMYxBDZ,iv:NWIvvXqNEGHNATZxrjCPjRJiZHnQsMawf08Nu/TY9Qw=,tag:g6Y1nZ0OpVseFuvvq65QPA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSmR5ZHZDY0VpaUxMOTlJ
            RU8xMVpZa1I1eHlqK0x0d2FDVTNRZVA0WkZFClQ1UzhFNnlCTVdjM2FBMjByUDlN
            dFlyK2RqNWpNME1RcDJsVE1CK3d6aVkKLS0tIE5TQmZQbkpRUUxiUEFYakp2THdn
            RHVURTJzRkJWZm1kQUl4S1ZUeWpNVnMKeGu54Y1yKrKXOxTAXLnFzslMXOnbrYFU
            dAEiD/rm5I9pV8vM/KWO5REP26ZxwJdg7rweqESbF86P56Bl+sLIkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T17:10:41Z"
    mac: ENC[AES256_GCM,data:01qH12ik0aacXIlpn8SAT/+yuzdHCRbf81eYsOd7nfWVynQF9GBicRwMLgW0cSuZNYBe5vLJRR91ODl0nnZFND8/oBONkkI8Wxrv6lz2+M7PmiwKmC4o/YyxToON17Mq0aXl1HnT45PKQEYaA1v1Ob1+USGiocUhhuw8aMxwj80=,iv:ceUYeFXsyRmNSekXMwXFe2yAPd9/JsHV2o7lo/vXwhc=,tag:OLtAg3iew4CswYhw8VUl+g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
