apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:B/Xg/hA6656xKv4xLUk4sOhZfMtrzGT0pnPlPazhBfXXDi4WW5+Nx/CftEo0yEK6JbjEYDv0FN/8ArRfT8K7D9JRDBmOgbp9iASN59FvoStjjQcmuCz+75NvP/fi6VgCOBEvr3RfoC7ph658tJpnmZLONMMpaSG+GRhw+6SLfufzSaYjFfrhW5R7VRtY/QUqcwKGb/s1wnMi9AWpg/aGA9PFuZ2lp3SGmYjHiEE4mOTDiPewrGP4N9Hrrll3lnfer7jrqVIMMd/neHl0oaKD/cVD5rxucWaN674jgico++cTeG01WWL1fzC7VaIv0ZDSh2/xqga4uz2z5mrC9proDGPdDvVLTcTjqslzmLPFqz5GCcH0DUIOu8lsJEf0OK+e,iv:hfM9zRBPwxoQUKwTWkFAKeusNeOTvnLZmdchpAum0/g=,tag:utibtdB2Z9OFCPsbV7eKaQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:8vICAAZ33yg6I/uJLd7r8r3H6bLhfbY/ToY5SS8iLhEwmL4e4399gUdm5z01j6gpYFxVC3qUOJXfG5WIDK9vMjptRmxAlWAiNwA3nTfMzWJOuQGgH3c/YpNKBirTqPgTjCysqcdc/hyA6u3Md5x9uns5HwNKYz6XWNM8bK2QAFUYou+gXKowi34AYlRpSOzumJwd/SftiPy6yZuwzjqJgY3zVMm8Yx8TY3vpP9Es9l7MDKDovy/8b2b7LZs3Ws2nmkbAXOu7WjkfXARDuw==,iv:ojcfmVOTBi8UlG8s0A5tfoHNZagBVEHQRHS5YtPzlsQ=,tag:Ocgzqn+3PFuFTq7KRkTQqg==,type:str]
    known_hosts: ENC[AES256_GCM,data:i2aqH+G5d3ANt9mosOwr2EEsEjkQIWZ3nhBUBOuCprqPUeSKz2THgGVB2lcGxe4RWG1yPkF7A96Z7Vg94VwKAAt5VDArnRgzGGvKhi4PxZhlLW/9DGfxqQOqvkE7oaaqRgNT6BBO/1/QMPDmy/IF1rYSeJTZfb0bUDuQ9GDhXmqpdroSok/if9kpplOg4cgBTmuAPPWsfhk6bxIp6dAbT4SK2/+HFVXneD5J,iv:Cj+TIhbrY90TiWK3GFjisOfFzjaR7YrLbyO3F1OIrGI=,tag:kU4LFuxYGrfKGtFJ68tC7Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSk93SUF2SHRFcjlwRkNQ
            UzYvNlNaTFNZMHY3ZWVvOFUzZXpnODZaS21vCmFhN0hnRVNMVTlCTk10OXUxTGdz
            YzE3aVh0dVFUdmYxMnRCQ0hMREo2SGcKLS0tIFFRSFhXN2NZcnl5K3FoSm85d0Y5
            TDNuYlBCUVJ4WDd1eW1DcXplU2ovNmMKOhnTbsjZHEQXL3GetTMqu5CbY4NOWM3O
            v0t/u2XrDRTORNjZHIxoReRpdDLkU+vnF/SdW1YUtHRTMlhFtYo1Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-24T15:49:39Z"
    mac: ENC[AES256_GCM,data:o+d7raZTo70mP/P9Dn2SdbEIk9TlhDXPJsaUHNO1GWEHti+ORBa/7i1noyZ88jWAC5D9Nz2LsXasi3YORj5jiUd/xjWC2GXs37FTczBy4pGIChQUYJQJdOB0urrQtKKXY37ZdldxbHWy3h/a+COHHoSJwrEgIxB2Bzb34A8x98I=,iv:SJp8JkyTM84LCDSPUIdTKZ3ZBCdjp/25c5GBidYgt6c=,tag:6qyDplJfpIKtj/qnfLnAqw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
