apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:QmI2Uvs03XqtYfJsMn4cCdAnacWyT6y7M4YFo3KsxyjwYBiCU+qXnMjlrtL6nOvmm+mo95JX2xSx7ZQeFuVxpmNDjaPmnz2uWiYGQzHIRn4ScZAU8IK7kfIDKGr6byXx7KeZlwVzbLfkqamVNpDK+1L2ozApQ3DI212ikITJYRfJgrJD7dXAiMvuIzoPhihNVgk61m/pZKPXLX69/OPDzSRsbuOm95RFxPZxEVuSlaidGNnYplpPZin9+KHgAYYntVB/6zVZJhSXfIqhA7628rUgoA35KUGqGR2myAUXQfn8d6Kg/9KEgNykisbOA2it+zFGSMN7ieF+/6UA7CnacdjCy9x7gHNYeLtKy10uuoatns6YbdHc9BMp4VL3GbRN,iv:mvL/pTuIvd813aVs6Of9ZUZ9Nb46WXVsHYylWB3h3tI=,tag:WLjONyOJ4FYtPTulSJ20Iw==,type:str]
    identity.pub: ENC[AES256_GCM,data:C7k26gmETEz4KSaoo/QBaGpNT8P59t0LN3hHFshKzc3qDWjXEQJW3V7e7vt3l1RjmeXF+SFlPpsJX++1qu73+aWtyihGjRpac1dqVQ8KsDg3ipzW1xa0iqB9taTN3wcILYxY6WEAP/rvWTMEpwFJ8HHugjS1VjjgjO6H/6vryHMt7Hug2AOC4nn4pln9vjIqJt8oLuXq3ERqQ5oUSAm7l3F+2zZvTqWvst1iSJGPRYoE3wj8Ng4M6x0zj0KCwOKrAUlOnQ2NJqFIW5JXJw==,iv:3JQEC0JDaWXVXURn9k1hLoKc61BA/qC+kp0ZpiBsdCQ=,tag:ERguh7Nj/5jjlkFWNEntzg==,type:str]
    known_hosts: ENC[AES256_GCM,data:I3f9ametn5spwmQ6kc3Qg4QZoELpEceReipOvMgWdRf0Kzo5DEBYJEYl8K1FfR6D0S6a6BJVm28lkL/vTlUYThDY3FNDAETz9EDHNhI0Qe5yUhaXGenMHalMz/m1EfRSNGBGPPIWar1wSRsvbLgqrKS+zhXx4fnW7oQaIelrhb3iJ3+YcQOlrSeHqjIXmH8DjxgJnOfo0f+7J0niV7IjP+PiGNmkvmlKWSvs,iv:i2FIR4/oCU+4KFwPbKki7ezJg8drx3ldP7XVs2wxvd0=,tag:k3/RE8XVxB1SRenwpdoKrg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDV3hmRDhSUXV3dExxRGZK
            NUZyTlpWR3JTcXU1MlNGWVROWUFwNzN0MlJzCmJUVjYxWUJhdDVoa1c2Z1o5bi80
            ak9NN1NGMXVPWmQwLzVKNGxKTHdteVEKLS0tIG1nWUc1NHRmenFHM0ZqQkJrM1Yr
            NTI4M01OUmFDZHBLbXRPakxhMXl5MzQKSbEYaFmyD+KrFM++/GJlE+4QXprJE/Hk
            XCzyXW0dOaafnR25MXWfJ0ymMVYv5rDXvCv0+9AqlzqGN1Z8klXvUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T21:45:53Z"
    mac: ENC[AES256_GCM,data:L/4lqbz82h+PHzx+8znH26kLi/0eFt59VX7Hp6xK/4AzTjZlXcJn7gZezl7Ze42DEGVWWneJ9L1a6ESOmuK5JM+NCQSnJx9pe0Agq+Fjvf6v1DE+7cmWJaMEspX3e0/l7oMDi3GOtY2w+hOS4ouIZEMaKQqsBAcRIXmhGpHZRXM=,iv:g0VsnzlRfhkQSOoWyd7JmzJwxZRteq3D8E3YZrWO3SM=,tag:eQz/83G5BBfiaNZs/LFWXw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
