apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc
  namespace: shoko
spec:
  storageClassName: media-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeName: nfs-media-pv 