apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:eTj8xylbWPaYSI1b+GvEux5UFuSnwlNC+KvhlC5Iep/UZiDsUOibIA==,iv:p7/xOvm9j3SJQ+YoEa8TU/93NPt1eJZKtfgUQb88UHI=,tag:ujy+Lwwm3JVQu63pVKImGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSellibldFMUwrMU1YRDlE
            TVUvZ3hOUmZBY2c3dm04ZlNCR0hreGozMnhRCnQwOHY1a1NKQ3RyQWc5eHBSVUZ3
            cDFpSDZjeDk2Q3dFclpkazZra3pqSlUKLS0tIEhQV1ZNaDNpNmE5VzhQNnhWUXNs
            Skk5clcydUpVS2VHVEFxVHlwZlJSQzgKHhgvA7Ii0zwPsMT7r1wFWRpZtI/67SQj
            +Y9ot27r8qr1qihFfvDPW7KesrWGKzw7IcnLVEQv/67k4RO8oA11YQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-10-04T06:31:39Z"
    mac: ENC[AES256_GCM,data:X4aVlPtIalZ+l937Q1w+o8cK1Gqr6uZZI/6zvYfY/p3gu5CRViUR3CX2+IfJkfkMexV/bP1ilv5Az0eHHLm003Ax9Zyg/c/rcut/AS/3oOWzx5olq3Pl/D4ps+EE3eTm3OnlNFBv5G4Rk2b7uG2u2U8a5XGQura1N/clkAWCAlY=,iv:cZoTobghPkujKEvYf+aYKUxuS+d/Yr8jHAkAUgtAvzk=,tag:KfJDew9tl4JYDBjK/90a5g==,type:str]
    shamir_threshold: 3
    version: 3.13.1
