apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Vnh8c7R1lnusitqmsA1FXoKJuoTq9OAlHtmBWqZxrDHAOhepFzNY7w==,iv:PZrjfHrGF/gFeWm+oL9GIB17YXfunkvvNeRmIFGphV0=,tag:Oo5FU99iJOJjUNOzxh1jBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M3R2S3BaZ2dubDZWcmJR
            TlFFV3hid0g5aUNYMnZ6akM0S0Zhd0hEQUFRCjJCTkU5SXdLZUlOSUVjNXBGS1Iw
            bFYrZmV1RVpGc2FDZm9RZWdKWXQvd2sKLS0tIGVRYWtTQkROaEo1S1ZPTm1TUmVz
            QS9veHlnTTMrNE01eHo3S0lReTMyMzQKouMLjzf8Ex7eHZS95XOf+Vt3mbeiooIN
            oYjPaHfJO3UwrGcm+dshgQ2P1TuXay4DRzXshewfQe0TVQgYx+eFhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-20T17:00:21Z"
    mac: ENC[AES256_GCM,data:2a1FDBuU34ZpGiivQiRD246nHE84SrtmFQ8bpkA2czjuvr4dReAwQ9CNoiTYAvquxMQv+OFbWiLAo4TkD991PrazKr2pCS44RRyPYZQqKl1mkDX7EFjowIEjH/3or2Wby2S03/8YsW3vW1pjAZa4c9w0mY2sNGVc4I7AZJSGToU=,iv:QXSv6zO8dtE/0nsBecgKwtMbf+7AnFina9BwXGdPPGU=,tag:pK4LfmQRQ3yIEKQWuEIgqQ==,type:str]
    shamir_threshold: 3
    version: 3.13.1
