apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:rwJI/haGLMChsYaYJi6r08V1F3H2r8Clab9vQUUXUxN+fumV5uUhkg==,iv:fS0UbrptpoEj0YqlZwjWpLONfAyXsRmy79vPc53OfAQ=,tag:nhivgopYW0PgVr62fwO7TA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiazM5cnd3VmY1NXBmY29O
            YU5tL3F6cHBLZ0VkbmdPTTdtL3NUWmQ3SDMwCm1WQUhzQ0hWOWpZSW4wdnBsWHBk
            bklLRjBPVnNHVklwbVQ4d0tXV3hQREkKLS0tIG92UVVJbjQ5ZkZPUEJjS05rVHRk
            ZnVZalBJWXJsclpJaXlqMkFpTExxdm8KS/uOBzzpk+Q8vQFhA3SigR2VuctkoocU
            simu9sJcGKsNMbKKK3cHrpbFMICqBSDiKVyG1KU2HZvfR1oUf0vDig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T09:03:31Z"
    mac: ENC[AES256_GCM,data:XIMXUwujHFP4n6Pp/pPqv1lYvqB8r5L9yCP6BNbNRsYL6fKwrLBRl+p93QXN7xRKojhtQRdNaaVo0O36esD/0Ot1MKReVtqqncI5n+UvnwvuGVYMT61g+oQLZFlYlE2RqGrNvmSlLHOwyvgFTwxqI1gUds7jYwrYSf/DFfEhPaI=,iv:knNb9Jw9CwqSnuH5glMXIA4V+v3xITdubEtzqnM9FOQ=,tag:H1cHREmwDgNFvQk28sJQ3g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
