apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: palworld
  namespace: palworld
spec:
  interval: 15m
  chart:
    spec:
      chart: palworld
      version: 7.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: palworld
  values:

    palworld:
      steam:
        id: "2394010"
        username: ""
        password: ""
        validate: false
      game:
        ServerName: "My Palworld Server"
        ServerDescription: "A Palworld Server running in Kubernetes"
        ServerPassword: "${PALWORLD_SERVER_PASSWORD}"
        AdminPassword: "${PALWORLD_ADMIN_PASSWORD}"
        bUseAuth: true
        # PublicIP: "my public IP"
        # AllowConnectPlatform: "Steam|Xbox"
      update_public_ip: false
      params:
        - -publiclobby
      params_extra:
        - -useperfthreads
        - -NoAsyncLoadingThread
        - -UseMultithreadForDS
      backup:
        enabled: true
        interval: 120
        to_keep: 12

    service:
      main:
        type: LoadBalancer
        ports:
          main:
            protocol: udp
            port: 8211

    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: pal.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix

    resources:
      limits:
        cpu: 6
        memory: 24Gi
      requests:
        cpu: 2
        memory: 6Gi
