apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: palworld
  namespace: palworld
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 18.14.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: palworld
  values:

    image:
      repository: ghcr.io/thijsvanloef/palworld-server-docker
      tag: v2.7.0
      pullPolicy: IfNotPresent

    service:
      main:
        type: LoadBalancer
        enabled: true
        ports:
          main:
            enabled: true
            protocol: udp
            port: 8211
            targetPort: 8211

      rcon:
        enabled: true
        ports:
          rcon:
            enabled: true
            protocol: tcp
            port: 25575
            targetPort: 25575

      query:
        enabled: true
        ports:
          query:
            enabled: true
            protocol: udp
            port: 27015
            targetPort: 27015

      api:
        enabled: true
        ports:
          api:
            enabled: true
            protocol: tcp
            port: 8212
            targetPort: 8212


    workload:
      main:
        podSpec:

          containers:
            main:

              env:

                # Steam
                PUID: "1000"
                PGID: "1000"

                STEAMCMD_APP_ID: "2394010"

                # Server settings
                SERVER_NAME: "A Palworld Server"
                SERVER_DESCRIPTION: "A Palworld Server running in Kubernetes"

                SERVER_PASSWORD: "${PALWORLD_SERVER_PASSWORD}"
                ADMIN_PASSWORD: "${PALWORLD_ADMIN_PASSWORD}"

                COMMUNITY_SERVER: "true"

                # RCON
                RCON_ENABLED: "true"
                RCON_PORT: "25575"
                RCON_PASSWORD: "${PALWORLD_ADMIN_PASSWORD}"

                # REST API
                REST_API_ENABLED: "true"
                REST_API_PORT: "8212"

                # Auto pause
                AUTO_PAUSE_ENABLED: "true"
                AUTO_PAUSE_TIMEOUT_EST: "180"
                AUTO_PAUSE_LOG: "true"
                AUTO_PAUSE_DEBUG: "true"

                # Performance
                ENABLE_PERF_THREADING_ARGS: true

                # Updates
                UPDATE_ON_BOOT: "true"
                AUTO_UPDATE_ENABLED: "false"
                AUTO_UPDATE_CRON_EXPRESSION: "0 * * * *"
                AUTO_UPDATE_WARN_MINUTES: "30"

                # Reboot
                AUTO_REBOOT_ENABLED: "false"
                AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE: "false"
                AUTO_REBOOT_WARN_MINUTES: "5"
                AUTO_REBOOT_CRON_EXPRESSION: "0 0 * * *"

              resources:
                requests:
                  cpu: 2
                  memory: 6Gi
                limits:
                  cpu: 6
                  memory: 24Gi

              securityContext:
                runAsUser: 0
                runAsGroup: 0
                runAsNonRoot: false
                readOnlyRootFilesystem: false
                allowPrivilegeEscalation: true
                capabilities:
                  add:
                    - CHOWN
                    - SETUID
                    - SETGID
                    - FOWNER
                    - DAC_OVERRIDE
                  drop:
                    - ALL

    persistence:
      palworld:
        enabled: true
        mountPath: /palworld/

    ingress:
      main:
        enabled: true
        ingressClassName: external

        hosts:
          - host: pal.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix